@startwbs "classes"

<style>
wbsDiagram {
  FontName monospaced
}
</style>

* CPack
** CPackForServer
***< ArrangeStacks
***> AssembleArtifacts
***< BuildBoat
***> BuildStructure
***< BulkExchangeArtifacts
***> BulkMergeStacks
***< BulkMoveArmy
***> BulkSmartSplitStack
***< BulkSplitStack
***> BuyArtifact
***< CastAdvSpell
***> CastleTeleportHero
***< DigWithHero
***> DisbandCreature
***< DismissHero
***> EndTurn
***< EraseArtifactByClient
***> ExchangeArtifacts
***< GarrisonHeroSwap
***> HireHero
***< MakeAction
***> MakeCustomAction
***< MoveHero
***> PlayerMessage
***< QueryReply
***> RecruitCreatures
***< SaveGame
***> SetFormation
***< TradeOnMarketplace
***> UpgradeCreature
** CPackForClient
***< AddQuest
***> AdvmapSpellCast
***< BattleAttack
***> BattleLogMessage
***< BattleNextRound
***> BattleObstaclesChanged
***< BattleResultAccepted
***> BattleResultsApplied
***< BattleSetActiveStack
***> BattleSetStackProperty
***< BattleSpellCast
***> BattleStackMoved
***< BattleStart
***> BattleTriggerEffect
***< BattleUnitsChanged
***> BattleUpdateGateState
***< CatapultAttack
***> CenterView
***< ChangeFormation
***> ChangeObjPos
***< ChangeObjectVisitors
***> ChangeSpells
***< EndAction
***> EntitiesChanged
***< FoWChange
***> GiveBonus
***< GiveHero
***> HeroRecruited
***< HeroVisit
***> HeroVisitCastle
***< InfoWindow
***> NewObject
***< NewStructures
***> NewTurn
***< OpenWindow
***> PackageApplied
***< PlayerBlocked
***> PlayerCheated
***< PlayerEndsGame
***> PlayerMessageClient
***< PlayerReinitInterface
***> PrepareHeroLevelUp
***< Query
***> RazeStructures
***< RemoveBonus
***> RemoveObject
***< SetAvailableArtifacts
***> SetAvailableCreatures
***< SetAvailableHero
***> SetCommanderProperty
***< SetHeroesInTown
***> SetMana
***< SetMovePoints
***> SetObjectProperty
***< SetPrimSkill
***> SetResources
***< SetSecSkill
***> SetStackEffect
***< ShowWorldViewEx
***> StacksInjured
***< StartAction
***> SystemMessage
***< TryMoveHero
***> UpdateArtHandlerLists
***< UpdateCastleEvents
***> UpdateMapEvents
***< YourTurn
** CPackForLobby
***< CLobbyPackToServer
****< LobbyChangePlayerOption
****> LobbyForceSetPlayer
****< LobbySetCampaign
****> LobbySetCampaignBonus
****< LobbySetCampaignMap
****> LobbySetDifficulty
****< LobbySetMap
****> LobbySetPlayer
**** LobbySetTurnTime
***> CLobbyPackToPropagate
****< LobbyChangeHost
****> LobbyChatMessage
****< LobbyClientConnected
****> LobbyClientDisconnected
****< LobbyEndGame
****> LobbyGuiAction
****< LobbyShowMessage
****> LobbyStartGame
****< LobbyUpdateState

@endwbs
