
@startuml "vcmi-1.32-communication-sequence-loadgame"

title "VCMI-1.3.2 communication sequence for loading a game"

skinparam DefaultTextAlignment center
skinparam DefaultFontName monospaced
skinparam SequenceDividerFontName SansSerif
skinparam NoteFontName SansSerif

participant Server as server
participant Client as client

== (in game)\n"Load Game" clicked ==

client -> server: LobbyClientDisconnected ~*
destroy client


== (in lobby)\nSavegame highlighted from the list ==

note across: XXX: use startgame diagram instead

client o-> server: LobbyClientConnected
server -> client: LobbyClientConnected
server -> client: LobbyUpdateState
client -> server: LobbySetMap
server -> client: LobbySetMap
server -> client: LobbyUpdateState

== (in lobby)\n"Load" clicked ==
client -> server: LobbyStartGame
server -> client: LobbyStartGame
|||
server -> client: YourTurn

@enduml
