@startuml "vcmi-1.32-threads-client"

skinparam defaultTextAlignment center

!procedure $desc($txt)
<font:Arial><color:Gray><i>// $txt</i></color></font>
!endprocedure

title "VCMI-1.3.2 class diagram (appliers)"

'''' Declarations to stylize the diagram ''''
hide circle
set namespaceSeparator none

skinparam ClassFontStyle bold
skinparam ClassFontName monospaced
skinparam ClassAttributeFontName monospaced
skinparam ClassAttributeIconSize 0
skinparam DefaultTextAlignment left


'''' Attributes and methods '''


class main {
    $desc("myclient.cpp:45")
}

main -- "CSimpleJoinScreen.connectThread()" : "New/Load Game clicked"

class "CSimpleJoinScreen.connectThread()" {
    $desc("CMainMenu.cpp:551")
}

"CSimpleJoinScreen.connectThread()" -- "CServerHandler.threadHandleConnection()" : "connected"

class "CServerHandler.threadHandleConnection()" {
    $desc("CServerHandler.cpp:306")
    $desc("receives CPacks from client")
}

@enduml
