@startuml "vcmi-1.32-reset-midbattle"

title "VCMI-1.3.2 connector reset (mid-battle)"
title "WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW"

skinparam sequenceBoxBorderColor #FFF

!$nbsp = "<U+00A0>"

' workaround the fact that text alignment can only be
' set globally. Using hspace(n) returns N monospaced
' $nbsp chars
!function $hspace($length)
  !$res = ""
  !$i = $length
  !while $i > 0
    !$res = $res + $nbsp
    !$i = $i - 1
  !endwhile
  !return "<font:monospaced>"+$res+"</font>"
!endfunction

!function $desc($txt)
  !return "<font:Arial><color:Gray><i>// "+$txt+"</i></color></font>"
!endfunction

!function $wait($type, $set)
  !if ($set == 0)
    !return "<back:red>"+$type+".wait()</back>"
  !endif

  !return "<color:yellow><back:blue>"+$type+".wait()</back></color>"
!endfunction

!function $cond_notify()
  !return "<color:blue>cond.notify()</color>"
!endfunction

!function $event_set()
  !return "<color:blue>event.set()</color>"
!endfunction

participant "//Env//" as env
participant "//AAI//" as AAI
participant "//BAI//" as BAI
participant "//VCMI//" as vcmi

activate env

env -> env : $wait(event,0)

vcmi -> BAI : activeStack
activate BAI
BAI -> env : resultcb()
activate env
env -> env : set result\n$event_set()
env --> BAI :
deactivate env
env -> env : $wait(event,1)

[<- env : obs
deactivate env

BAI -> BAI : $wait(cond,0)

[-> env : .reset()
activate env

env -> AAI : resetcb()
activate AAI
AAI -> BAI : actioncb\n$desc(retreat)
activate BAI
BAI -> BAI : set action\n$desc(retreat)
BAI -> BAI : $cond_notify()
BAI --> AAI :
deactivate BAI
AAI --> env :
deactivate AAI
BAI -> BAI : $wait(cond,1)
env -> env : $wait(event,0)
BAI -> vcmi : makeAction()\n$desc(retreat)
BAI --> BAI : $desc(return)

deactivate BAI
vcmi -> AAI : battleEnd()
activate AAI
AAI -> AAI : awaitingReset=true
AAI -> vcmi : selectionMade\n$desc(replay)
note right of vcmi
battle restart in progress
battleStart packets are sent
(but not received by AAI which is blocked)
end note

AAI -> BAI : battleEnd()\n$desc("through CAdventureAI")
activate BAI

BAI -> env : resultcb()
activate env
env -> env : set result\n$event_set()
env --> BAI :
deactivate env

BAI --> AAI :
deactivate BAI

env -> env : $wait(event,1)
[<- env : obs
deactivate env

[-> env : .step()
activate env
env -> BAI : actioncb()
activate BAI
AAI -> BAI : <<destroy>>\n$desc("through CAdventureAI")
destroy BAI
note over BAI #orange : UB
AAI -> AAI : $wait(event, 0)
note over AAI : (blocked forever)



@enduml
